version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eicore

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

