spring:
  application:
    name: eicore
  datasource:
    url: jdbc:mysql://localhost:3306/eicore
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
  docker:
    compose:
      lifecycle-management: start_only
      enabled: false
  cache:
    type: redis
jwt:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
vaadin:
  urlMapping: "/ui/*"
